app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::get('/', ['uses' => 'LoginController@index', 'as' => 'login']);
Route::post('/auth/login', ['uses' => 'LoginController@login', 'as' => 'auth.login']);
Route::get('/auth/logout', ['uses' => 'LoginController@logout', 'as' => 'auth.logout']);

Route::group(['middleware' => ['auth', 'role:teacher|student']], function () {
	Route::put('/auth/profile', ['uses' => 'LoginController@update', 'as' => 'auth.update']);
	Route::put('/auth/password', ['uses' => 'LoginController@passwordUpdate', 'as' => 'auth.updatepassword']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::put('/auth/image', ['uses' => 'LoginController@changeImage', 'as' => 'auth.image']);
});

Route::post('/password/email', ['uses' => 'Auth\PasswordController@postEmail', 'as' => 'email.store']);
Route::get('/password/reset/{token}', ['uses' => 'Auth\PasswordController@getReset', 'as' => 'reset.request']);
Route::post('/password/reset', ['uses' => 'Auth\PasswordController@postReset', 'as' => 'reset.store']);

Route::group(['prefix' => '/lms-admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:staff']], function () {
	Route::get('/', ['uses' => 'HomeController@index', 'as' => 'lms-admin.index'] );
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'lms-admin.profile']);
	
	Route::resource('/users', 'UserController', ['except' => 'show']);
	Route::patch('users/{users}/usermeta', ['uses' => 'UserController@updateMeta', 'as' => 'lms-admin.users.updatemeta']);
	Route::resource('/majors', 'MajorController', ['except' => 'show']);
	Route::resource('/subjects', 'SubjectController', ['except' => 'show']);
	Route::resource('/announcements', 'AnnouncementController', ['except' => 'show']);
	Route::resource('/classrooms', 'ClassroomController', ['except' => 'show']);
	Route::post('/classrooms/addmembers', ['uses' => 'ClassroomController@addMembers', 'as' => 'lms-admin.classrooms.addmembers']);
	Route::post('/classrooms/removemember', ['uses' => 'ClassroomController@removeMember', 'as' => 'lms-admin.classrooms.removemember']);
});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
	Route::get('/{username}/profile', ['uses' => 'HomeController@friend', 'as' => 'home.friend']);
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'home.profile']);
	Route::get('/password', ['uses' => 'HomeController@password', 'as' => 'home.password']);
	Route::get('/calendar', ['uses' => 'HomeController@calendar', 'as' => 'home.calendar']);
	Route::get('/all-announcements', ['uses' => 'AnnouncementController@index', 'as' => 'home.announcements']);
	Route::get('/all-online', ['uses' => 'HomeController@online', 'as' => 'home.onlines']);
	Route::get('/all-assignments', ['uses' => 'AssignmentController@assignments', 'as' => 'home.assignments']);

	Route::get('/classrooms/{classrooms}', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.show']);
	Route::get('/classrooms/{classrooms}/edit', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.user.edit']);
	Route::post('/classrooms/{classrooms}', ['uses' => 'ClassroomController@update', 'as' => 'classrooms.user.update']);
	Route::get('/classrooms/{classrooms}/courses', ['uses' => 'ClassroomController@courses', 'as' => 'classrooms.courses']);
	Route::get('/classrooms/{classrooms}/assignments', ['uses' => 'ClassroomController@assignments', 'as' => 'classrooms.assignments']);
	Route::get('/classrooms/{classrooms}/quizzes', ['uses' => 'ClassroomController@quizzes', 'as' => 'classrooms.quizzes']);
	Route::get('/classrooms/{classrooms}/members', ['uses' => 'ClassroomController@members', 'as' => 'classrooms.members']);

	Route::get('/classrooms/{classrooms}/discuss/{discuss}', ['uses' => 'ClassroomController@discussionDetail', 'as' => 'classrooms.discussiondetail']);
	Route::get('/classrooms/{classrooms}/assignments/{assignments}', ['uses' => 'ClassroomController@assignmentDetail', 'as' => 'classrooms.assignmentdetail']);
	Route::get('/classrooms/{classrooms}/courses/{courses}', ['uses' => 'ClassroomController@courseDetail', 'as' => 'classrooms.coursedetail']);
	Route::get('/classrooms/{classrooms}/modules/{modules}', ['uses' => 'ClassroomController@moduleDetail', 'as' => 'classrooms.moduledetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}', ['uses' => 'ClassroomController@quizDetail', 'as' => 'classrooms.quizdetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}/score', ['uses' => 'ClassroomController@score', 'as' => 'classrooms.score']);
	Route::get('/classrooms/download/{filename}', ['uses' => 'ClassroomController@download', 'as' => 'classrooms.download']);

	Route::resource('/discuss', 'DiscussionController', ['only' => ['store', 'destroy']]);
	Route::post('/submission', ['uses' => 'ClassroomController@attachSubmission', 'as' => 'submissions.store']);
	Route::delete('/submission', ['uses' => 'ClassroomController@detachSubmission', 'as' => 'submissions.destroy']);

});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher']], function () {
	Route::resource('/assignments', 'AssignmentController', ['except' => 'show']);
	Route::post('/assignments/attach', ['uses' => 'AssignmentController@attachTo', 'as' => 'assignments.attach']);
	Route::post('/assignments/detach', ['uses' => 'AssignmentController@detachFrom', 'as' => 'assignments.detach']);
	
	Route::resource('/courses', 'CourseController', ['except' => 'show']);
	Route::post('/courses/attach', ['uses' => 'CourseController@attachTo', 'as' => 'courses.attach']);
	Route::post('/courses/detach', ['uses' => 'CourseController@detachFrom', 'as' => 'courses.detach']);

	Route::resource('/modules', 'ModuleController', ['except' => ['index', 'create', 'show']]);

	Route::resource('/quizzes', 'QuizController', ['except' => 'show']);
	Route::resource('/quizzes.mc', 'MultipleChoiceController', ['except' => ['index', 'show']]);
	Route::post('/quizzes/attach', ['uses' => 'QuizController@attachTo', 'as' => 'quizzes.attach']);
	Route::post('/quizzes/detach', ['uses' => 'QuizController@detachFrom', 'as' => 'quizzes.detach']);
});

Route::group(['prefix' => '/api', 'namespace' => 'API', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/assignments', 'AssignmentController@deadline');
	Route::post('/quizzes/start', 'QuizController@startQuiz');
	Route::post('/quizzes/submit', 'QuizController@submitQuiz');
	Route::post('/users/status', 'UserController@toggleStatus');
});

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
	public function toggleStatus(Request $request)
	{
		$this->validate($request, [
      'user_id' => 'required|exists:users,id'
    ]);

    $user = User::findOrFail($request->user_id);

    if($user->status === 'active') {
      $user->status = 'banned';
    } else {
      $user->status = 'active';
    }

    $user->save();

    return response()->json([
      'user_status' => $user->status
    ]);
	}
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Role;
use App\Models\User;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;

class UserController extends Controller
{
	public function index(Request $request)
	{
		$querystring = $this->buildQueryString($request);
		$users = $this->buildIndexQuery($request);
		$page_title = $request->has('q') ? 'Pencarian ' . $request->q : 'Semua Users';
		
		return view('admin.users.index', compact('users', 'querystring', 'page_title'));
	}

	public function buildQueryString($request)
	{
		$querystring = null;

		if( $request->has('type') ) {
			$querystring['type'] = $request->has('type') ? $request->type : '';
		} elseif($request->has('q')) {
			$querystring['q'] = $request->has('q') ? $request->q : '';
		}

		return $querystring;
	}

	public function buildIndexQuery($request)
	{
		if( $request->has('type') ) {            
			$users = User::where('role', $request->type)
				->orderBy('created_at', 'DESC')
				->paginate(7);
		} elseif( $request->has('q') ){
			$users = User::where(function($query) use ($request){
				$query->where('firstname', 'LIKE', '%' . $request->q . '%')
					->orWhere('lastname', 'LIKE', '%' . $request->q . '%')
					->orWhere('email', 'LIKE', '%' . $request->q . '%');
			})->orderBy('created_at', 'DESC')->paginate(7);
		} else {
			$users = User::orderBy('created_at', 'DESC')->paginate(7);
		}

		return $users;
	}

	public function create(Request $request)
	{
		$users = User::orderBy('created_at', 'DESC')->paginate(7);

		$page_title = $request->has('type') ? ucfirst($request->type) : 'User';
		return view('admin.users.create', compact('users', 'page_title'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'username' => 'required|unique:users,username',
			'firstname' => 'required',
			'lastname' => 'required',
			'email' => 'required|email|unique:users,email'
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!',
			'email' => 'Kolom :attribute harus berupa email.'
		]);

		$data = $request->all();
		//default password
		$data['password'] = bcrypt('secret');

		$user = User::create($data);

		$user->usermeta()->create([
			'picture' => 'icon-user-default.png',
			'cover' => 'cover-default.jpg'
		]);

		\Flash::success('User tersimpan.');
		return redirect()->route('lms-admin.users.edit', [$user->id]);
	}

	public function edit(Request $request, $id)
	{
		$users = User::orderBy('created_at', 'DESC')->paginate(7);
		$page_title = 'Edit User';
		$user = User::findOrFail($id);

		return view('admin.users.edit', compact('users', 'user', 'page_title'));
	}

	public function update(Request $request, $id)
	{
		$user = User::findOrFail($id);

		$this->validate($request, [
			'username' => 'required|unique:users,username,' . $user->id,
			'firstname' => 'required',
			'lastname' => 'required',
			'email' => 'required|email|unique:users,email,' . $user->id,
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!',
			'email' => 'Kolom :attribute harus berupa email.'
		]);
		
		$user->update($request->all());

		\Flash::success('User diperbaharui.');
		return redirect()->back();
	}

	public function updateMeta(Request $request, $id)
	{
		$user = User::findOrFail($id);

		if(!$user->hasRole('student')) {
			$request->except(['nis', 'nisn', 'orangtua', 'wali', 'telp_orangtua']);
		}

		$user->usermeta->update($request->all());

		\Flash::success('User diperbaharui.');
		return redirect()->back();
	}
	
	public function destroy($id)
	{
		User::findOrFail($id)->delete();

		\Flash::success('User berhasil dihapus.');
		return redirect()->back();
	}

}

app/Http/Controllers/User/AnnouncementController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Announcement;
use Illuminate\Http\Request;

class AnnouncementController extends Controller
{
  public function index()
  {
  	$announcements = Announcement::orderBy('created_at', 'DESC')->paginate(10);
  	$page_title = 'Pengumuman';

  	return view('user.global.announcements', compact('announcements', 'page_title'));
  }
}

app/Http/Controllers/User/AssignmentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Activity;
use App\Models\Assignment;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class AssignmentController extends Controller
{
	public function index(Request $request)
	{
		$assignments = $request->user()
			->teacherassignments()
			->orderBy('created_at', 'DESC')
			->paginate(7);
		$page_title = 'Perpustakaan - Tugas';

		return view('user.assignments.index', compact('assignments','page_title'));
	}

	public function create()
	{
		$page_title = 'Tugas Baru';

		return view('user.assignments.create', compact('page_title'));		
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'title' => 'required',
			'file' => 'max:10000|mimes:pdf,docx,doc,zip',
			'content' => 'required'
		], [
			'required' => 'Kolom :attribute diperlukan',
		]);

		$data = $request->except('file');

		if($request->hasFile('file')) {
			$data['file'] = $this->upload($request->file('file'));
		}

		$assignment = $request->user()
			->teacherassignments()
			->create($data);

		\Flash::success('Tugas berhasil ditambahkan.');

		return redirect()->route('assignments.edit', $assignment);
	}

	public function edit(Request $request, $id)
	{
		$assignment = $request->user()
			->teacherassignments()
			->where('id', $id)
			->first();
		$ids = $assignment->attachedTo;
		$attached = $assignment->attachedClassroom;

		$page_title = $assignment->title;

		return view('user.assignments.edit', compact('assignment', 'page_title', 'attached', 'ids'));
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'title' => 'required',
			'file' => 'max:10000|mimes:pdf,docx,doc,zip',
			'content' => 'required'
		], [
			'required' => 'Kolom :attribute diperlukan'
		]);

		$assignment = $request->user()
			->teacherassignments()
			->where('id', $id)
			->first();
		$data = $request->except('file');
		$file = public_path( 'uploads/assignments/' . $assignment->file );

		if($request->hasFile('file')) {
			if(file_exists($file) && $assignment->file !== '') {
				unlink( $file );
			}

			$data['file'] = $this->upload($request->file('file'));
		}

		$assignment->update($data);

		\Flash::success('Tugas berhasil diupdate.');
		return redirect()->back();
	}

	public function destroy(Request $request, $id)
	{
		$assignment = $request->user()
			->teacherassignments()
			->where('id', $id)
			->first();
		$file = public_path( 'uploads/assignments/' . $assignment->file );
		
		if($assignment->file && file_exists($file)) {
			unlink( $file );
		}

		$assignment->delete();

		\Flash::success('Tugas berhasil dihapus.');
		return redirect()->back();
	}

	public function attachTo(Request $request)
	{
		$this->validate($request, [
			'classroom_id' => 'required|exists:classrooms,id',
			'assignment_id' => 'required|exists:assignments,id',
			'deadline' => 'required',
		], [
			'required' => 'Kolom :attribute diperlukan'
		]);

		$assignment = Assignment::findOrFail($request->assignment_id);

		Activity::create([
			'teacher_id' => $request->user()->id,
			'classroom_id' => $request->classroom_id,
			'action' => 'Membagikan tugas ke ',
			'route' => 'classrooms.assignmentdetail',
			'detail' => $assignment->id
		]);

		$assignment->classrooms()
			->sync([$request->classroom_id => ['deadline' => $request->deadline]], false);

		\Flash::success('Tugas berhasil dibagikan.');

		return redirect()->back();
	}

	public function detachFrom(Request $request)
	{
		$this->validate($request, [
			'classroom_id' => 'required',
			'assignment_id' => 'required',
		], [
			'required' => 'Kolom :attribute diperlukan'
		]);

		Assignment::findOrFail($request->assignment_id)
			->classrooms()
			->detach($request->classroom_id);

		\Flash::success('Tugas berhasil batalkan.');

		return redirect()->back();
	}

	public function upload(UploadedFile $file)
	{
		$original = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
		$sanitize = preg_replace('/[^a-zA-Z0-9]+/', '-', $original);
		$fileName = $sanitize . '.' . $file->getClientOriginalExtension();
		$destination = public_path() . DIRECTORY_SEPARATOR . 'uploads/assignments';

		$uploaded = $file->move($destination, $fileName);

		return $fileName;
	}

	public function assignments(Request $request)
	{
		$classrooms = $request->user()->hasRole('teacher') ? $request->user()->teacherclassrooms : $request->user()->classrooms;
		$page_title = 'Semua Tugas';
		$ids = $classrooms->map(function($class){
			return $class->id;
		})->toArray();

		$assignments = Assignment::whereHas('classrooms', function($q) use ($ids) {
			$q->where('deadline', '>=', date('Y-m-d'));
			$q->whereIn('id', $ids);
		})->paginate(10);

  	return view('user.global.assignments', compact('assignments', 'page_title'));
	}
}

resources/views/user/quizzes/create.blade.php
@extends('user.app')

@section('content')	
	<div class="container libraries">
		<div class="row">
			<div class="col-sm-4 col-md-2 hidden-xs">
				@include('user.global.sidebars._sidebar-left')
			</div>
			<div class="col-md-10">		
				<div class="profile-form panel panel-default">
					<header class="panel-heading">
						<h2 class="panel-title text-bold">{{ $page_title }}</h2>
					</header>
					<div class="panel-body">
						{!! Form::open(['route' => 'quizzes.store']) !!}
							@include('user.quizzes._form')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/user/quizzes/edit-mc.blade.php
@extends('user.app')

@section('content')	
	<div class="container libraries">
		<div class="row">
			<div class="col-sm-4 col-md-2 hidden-xs">
				@include('user.global.sidebars._sidebar-left')
			</div>
			<div class="col-md-10">
				<div class="profile-form panel panel-default">
					<header class="panel-heading">
						<h2 class="panel-title text-bold">{{ $page_title }}</h2>
					</header>
					<div class="panel-body">
						{!! Form::model($question, ['route' => ['quizzes.mc.update', $quiz->id, $question->id], 'method' => 'put', 'class' => 'multiple-choice-form']) !!}
							@include('user.quizzes._form-edit-mc', ['model' => $question])
							<a class="btn btn-danger btn-flat" href="{{ route('quizzes.edit', $quiz->id) }}"><i class="fa fa-times"></i> Batal</a>
							{!! Form::button('<i class="fa fa-save"></i> Update', ['class'=>'btn btn-flat btn-success', 'type' => 'submit']) !!}
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/user/quizzes/edit.blade.php
@extends('user.app')

@section('content')	
	<div class="container libraries">
		<div class="row">
			<div class="col-sm-4 col-md-2 hidden-xs">
				@include('user.global.sidebars._sidebar-left')
			</div>
			<div class="col-md-10">		
				<div class="profile-form panel panel-default">
					<header class="panel-heading">
						<h2 class="panel-title text-bold">{{ $page_title }}</h2>
					</header>
					<div class="panel-body">
						{!! Form::model($quiz, ['route' => ['quizzes.update', $quiz], 'method' =>'put', 'role' => 'form']) !!}
							@include('user.quizzes._form', ['model' => $quiz])
						{!! Form::close() !!}
					</div>
				</div>

				<div class="profile-form panel panel-default">
					<header class="panel-heading">
						<h2 class="panel-title text-bold">Pertanyaan</h2>
					</header>
					<div class="panel-body">
						<div class="share-to">					
							<a class="btn btn-primary btn-sm" href="{{ route('quizzes.mc.create', $quiz->id) }}"><i class="fa fa-plus"></i> Pertanyaan</a>
						</div>						
						<ul class="list-group module-list">
							@forelse($quiz->multiplechoices as $no => $mc)
								<li class="list-group-item">
									{{ $no + 1 }}. {{ strlen($mc->question) > 50 ? substr($mc->question, 0, 50) . '...' : $mc->question }}
									<span class="pull-right">
										<a href="{{ route('quizzes.mc.edit', [$quiz->id, $mc->id]) }}" class="btn-link btn-sm">Edit</a>
										{!! Form::open(['route' => ['quizzes.mc.destroy', $quiz->id, $mc->id], 'method' => 'delete', 'class' => 'element-inline']) !!}
											{!! Form::button('Delete', ['class' => 'btn-link btn-link-danger btn-sm warning-delete', 'type' => 'submit', 'data-title' => $mc->question]) !!}
										{!! Form::close() !!}
									</span>
								</li>
							@empty
								<li class="list-group-item text-center">Belum ada pertanyaan untuk quiz ini. <a href="{{ route('quizzes.mc.create', $quiz->id) }}" class="btn-link">Tambahkan</a></li>
							@endforelse
						</ul>
					</div>
				</div>

				<div class="profile-form panel panel-default">
					<header class="panel-heading">
						<h2 class="panel-title text-bold">Bagikan ke Tiap Kelas</h2>
					</header>
					<div class="panel-body">
						<div class="share-to">					
							<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#quizzesModal"><i class="fa fa-share-alt"></i> Bagikan</button>
						</div>
						<table class="table table-stripped">
							<thead>
								<tr>
									<th>Nama Kelas</th>
									<th>Batal</th>
								</tr>
							</thead>
							<tbody>							
								@forelse($quiz->classrooms as $classroom)
									<tr>
										<td>{{ $classroom->classname }}</td>
										<td>
											{!! Form::open(['route' => 'quizzes.detach']) !!}
												{!! Form::hidden('classroom_id', $classroom->id) !!}
												{!! Form::hidden('quiz_id', $quiz->id) !!}
												{!! Form::submit('Batal', ['class' => 'btn btn-danger btn-sm']) !!}
											{!! Form::close() !!}
										</td>
									</tr>
								@empty
									<tr>
										<td colspan="3" class="text-center">Belum pernah dibagikan.</td>
									</tr>
								@endforelse
							</tbody>
							<tfoot>
								<tr>
									<th>Nama Kelas</th>
									<th>Batal</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" id="quizzesModal" tabindex="-1" role="dialog" aria-labelledby="shareQuiz">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="shareQuiz">Bagikan quiz ini</h4>
				</div>
				{!! Form::open(['route' => ['quizzes.attach'], 'method' => 'post', 'role' => 'form', 'class' => 'form-horizontal']) !!}
					<div class="modal-body clearfix">
						<div class="col-md-12">
							{!! Form::hidden('quiz_id', $quiz->id) !!}
							<div class="form-group {{ $errors->has('classroom_id') ? 'has-error' : '' }}"> 
							{!! Form::select('classroom_id', $lms['profile']->teacherclassrooms()->whereNotIn('id', $ids)->get()->pluck('classname', 'id'), null, ['class' => 'select2 form-control', 'placeholder' => 'Pilih kelas...']) !!}
							{!! $errors->first('classroom_id', '<p class="help-block">:message</p>') !!}
							</div>
						</div>
					</div>
					<div class="modal-footer">
						{!! Form::button('Batal', ['class' => 'btn btn-link', 'data-dismiss' => 'modal']) !!}
						{!! Form::button('<i class="fa fa-share-alt"></i> Bagikan Quiz', ['class' => 'btn btn-primary', 'type' => 'submit']) !!}
					</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
@endsection

resources/views/user/quizzes/index.blade.php
@extends('user.app')

@section('content')	
	<div class="container libraries">
		<div class="row">
			<div class="col-sm-4 col-md-2 hidden-xs">
				@include('user.global.sidebars._sidebar-left')
			</div>
			<div class="col-md-10">		
				<div class="profile-form panel panel-default">
					<header class="panel-heading">
						<a href="{{ route('quizzes.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Quiz Baru</a>
					</header>
					<div class="panel-body">
						@forelse($quizzes as $quiz)
							<div class="panel panel-primary panel-sm">
								<header class="panel-heading">
									<h2 class="panel-title text-bold">{{ $quiz->title }}</h2>
								</header>
								<ul class="list-group">
									<li class="list-group-item"><strong>Total soal: </strong>{{ $quiz->multiplechoices->count() }} soal.</li>
									<li class="list-group-item"><strong>Waktu: </strong>{{ $quiz->time_limit }} menit.</li>
									<li class="list-group-item"><strong>Nilai minimal yang harus dicapai: </strong>{{ $quiz->pass_score }}.</li>
								</ul>
								<div class="panel-footer text-right">
									<a href="{{ route('quizzes.edit', $quiz->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
									{!! Form::open(['route' => ['quizzes.destroy', $quiz->id], 'method' => 'delete', 'class' => 'element-inline']) !!}
										{!! Form::button('<i class="fa fa-trash"></i>', ['class' => 'btn btn-danger btn-sm warning-delete', 'type' => 'submit', 'data-title' => $quiz->title]) !!}
									{!! Form::close() !!}
								</div>
							</div>
						@empty
							<div class="panel panel-default">
								<div class="panel-body text-center">
									Tidak ada quiz sama sekali. <a href="{{ route('quizzes.create') }}" class="btn-link">Buat quiz baru sekarang.</a>
								</div>
							</div>
						@endforelse
					</div>
					<div class="panel-footer clearfix">
						<div class="pull-right nomargin-paginator">
							{{ $quizzes->links() }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection