app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::get('/', ['uses' => 'LoginController@index', 'as' => 'login']);
Route::post('/auth/login', ['uses' => 'LoginController@login', 'as' => 'auth.login']);
Route::get('/auth/logout', ['uses' => 'LoginController@logout', 'as' => 'auth.logout']);

Route::group(['middleware' => ['auth', 'role:teacher|student']], function () {
	Route::put('/auth/profile', ['uses' => 'LoginController@update', 'as' => 'auth.update']);
	Route::put('/auth/password', ['uses' => 'LoginController@passwordUpdate', 'as' => 'auth.updatepassword']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::put('/auth/image', ['uses' => 'LoginController@changeImage', 'as' => 'auth.image']);
});

Route::post('/password/email', ['uses' => 'Auth\PasswordController@postEmail', 'as' => 'email.store']);
Route::get('/password/reset/{token}', ['uses' => 'Auth\PasswordController@getReset', 'as' => 'reset.request']);
Route::post('/password/reset', ['uses' => 'Auth\PasswordController@postReset', 'as' => 'reset.store']);

Route::group(['prefix' => '/lms-admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:staff']], function () {
	Route::get('/', ['uses' => 'HomeController@index', 'as' => 'lms-admin.index'] );
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'lms-admin.profile']);
	
	Route::resource('/users', 'UserController', ['except' => 'show']);
	Route::patch('users/{users}/usermeta', ['uses' => 'UserController@updateMeta', 'as' => 'lms-admin.users.updatemeta']);
	Route::resource('/majors', 'MajorController', ['except' => 'show']);
	Route::resource('/subjects', 'SubjectController', ['except' => 'show']);
	Route::resource('/announcements', 'AnnouncementController', ['except' => 'show']);
	Route::resource('/classrooms', 'ClassroomController', ['except' => 'show']);
	Route::post('/classrooms/addmembers', ['uses' => 'ClassroomController@addMembers', 'as' => 'lms-admin.classrooms.addmembers']);
	Route::post('/classrooms/removemember', ['uses' => 'ClassroomController@removeMember', 'as' => 'lms-admin.classrooms.removemember']);
});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
	Route::get('/{username}/profile', ['uses' => 'HomeController@friend', 'as' => 'home.friend']);
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'home.profile']);
	Route::get('/password', ['uses' => 'HomeController@password', 'as' => 'home.password']);
	Route::get('/calendar', ['uses' => 'HomeController@calendar', 'as' => 'home.calendar']);
	Route::get('/all-announcements', ['uses' => 'AnnouncementController@index', 'as' => 'home.announcements']);
	Route::get('/all-online', ['uses' => 'HomeController@online', 'as' => 'home.onlines']);
	Route::get('/all-assignments', ['uses' => 'AssignmentController@assignments', 'as' => 'home.assignments']);

	Route::get('/classrooms/{classrooms}', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.show']);
	Route::get('/classrooms/{classrooms}/edit', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.user.edit']);
	Route::post('/classrooms/{classrooms}', ['uses' => 'ClassroomController@update', 'as' => 'classrooms.user.update']);
	Route::get('/classrooms/{classrooms}/courses', ['uses' => 'ClassroomController@courses', 'as' => 'classrooms.courses']);
	Route::get('/classrooms/{classrooms}/assignments', ['uses' => 'ClassroomController@assignments', 'as' => 'classrooms.assignments']);
	Route::get('/classrooms/{classrooms}/quizzes', ['uses' => 'ClassroomController@quizzes', 'as' => 'classrooms.quizzes']);
	Route::get('/classrooms/{classrooms}/members', ['uses' => 'ClassroomController@members', 'as' => 'classrooms.members']);

	Route::get('/classrooms/{classrooms}/discuss/{discuss}', ['uses' => 'ClassroomController@discussionDetail', 'as' => 'classrooms.discussiondetail']);
	Route::get('/classrooms/{classrooms}/assignments/{assignments}', ['uses' => 'ClassroomController@assignmentDetail', 'as' => 'classrooms.assignmentdetail']);
	Route::get('/classrooms/{classrooms}/courses/{courses}', ['uses' => 'ClassroomController@courseDetail', 'as' => 'classrooms.coursedetail']);
	Route::get('/classrooms/{classrooms}/modules/{modules}', ['uses' => 'ClassroomController@moduleDetail', 'as' => 'classrooms.moduledetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}', ['uses' => 'ClassroomController@quizDetail', 'as' => 'classrooms.quizdetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}/score', ['uses' => 'ClassroomController@score', 'as' => 'classrooms.score']);
	Route::get('/classrooms/download/{filename}', ['uses' => 'ClassroomController@download', 'as' => 'classrooms.download']);

	Route::resource('/discuss', 'DiscussionController', ['only' => ['store', 'destroy']]);
	Route::post('/submission', ['uses' => 'ClassroomController@attachSubmission', 'as' => 'submissions.store']);
	Route::delete('/submission', ['uses' => 'ClassroomController@detachSubmission', 'as' => 'submissions.destroy']);

});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher']], function () {
	Route::resource('/assignments', 'AssignmentController', ['except' => 'show']);
	Route::post('/assignments/attach', ['uses' => 'AssignmentController@attachTo', 'as' => 'assignments.attach']);
	Route::post('/assignments/detach', ['uses' => 'AssignmentController@detachFrom', 'as' => 'assignments.detach']);
	
	Route::resource('/courses', 'CourseController', ['except' => 'show']);
	Route::post('/courses/attach', ['uses' => 'CourseController@attachTo', 'as' => 'courses.attach']);
	Route::post('/courses/detach', ['uses' => 'CourseController@detachFrom', 'as' => 'courses.detach']);

	Route::resource('/modules', 'ModuleController', ['except' => ['index', 'create', 'show']]);

	Route::resource('/quizzes', 'QuizController', ['except' => 'show']);
	Route::resource('/quizzes.mc', 'MultipleChoiceController', ['except' => ['index', 'show']]);
	Route::post('/quizzes/attach', ['uses' => 'QuizController@attachTo', 'as' => 'quizzes.attach']);
	Route::post('/quizzes/detach', ['uses' => 'QuizController@detachFrom', 'as' => 'quizzes.detach']);
});

Route::group(['prefix' => '/api', 'namespace' => 'API', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/assignments', 'AssignmentController@deadline');
	Route::post('/quizzes/start', 'QuizController@startQuiz');
	Route::post('/quizzes/submit', 'QuizController@submitQuiz');
	Route::post('/users/status', 'UserController@toggleStatus');
});

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\UuidModel;

class Subject extends Model
{

	use UuidModel;

	public $incrementing = false;
	
	protected $fillable = [
		'name', 'description'
	];

	protected $hidden = [
		'id', 'created_at', 'updated_at'
	];
}

app/Http/Controllers/Admin/SubjectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Subject;
use Illuminate\Http\Request;

class SubjectController extends Controller
{
	public function index(Request $request)
	{
		$subjects = Subject::where('name', 'LIKE', '%' . $request->q . '%')
			->orWhere('description', 'LIKE', '%' . $request->q . '%')
			->orderBy('created_at', 'DESC')->paginate(7);
		$page_title = 'Semua Mata Pelajaran';

		return view('admin.subjects.index', compact('subjects', 'page_title'));
	}

	public function create()
	{
		$subjects = Subject::orderBy('created_at', 'DESC')->paginate(7);
		$page_title = 'Tambah Mata Pelajaran';

		return view('admin.subjects.create', compact('subjects', 'page_title'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'name' => 'required',
			'description' => 'required'
		], [
			'required' => 'Kolom :attribute diperlukan!'
		]);

		$subject = Subject::create($request->all());

		\Flash::success('Mata pelajaran berhasil ditambah.');
		return redirect()->route('lms-admin.subjects.edit', [$subject->id]);
	}

	public function edit($id)
	{
		$subject = Subject::findOrFail($id);
		$subjects = Subject::orderBy('created_at', 'DESC')->paginate(7);
		$page_title = 'Edit Mata Pelajaran';

		return view('admin.subjects.edit', compact('subjects', 'subject', 'page_title'));
	}

	public function update(Request $request, $id)
	{
		$subject = Subject::findOrFail($id);

		$this->validate($request, [
			'name' => 'required',
			'description' => 'required'
		], [
			'required' => 'Kolom :attribute diperlukan!'
		]);

		$subject->update($request->all());

		\Flash::success('Mata pelajaran berhasil diubah.');
		return redirect()->back();
	}

	public function destroy($id)
	{
		Subject::findOrFail($id)->delete();

		\Flash::success('Mata pelajaran berhasil dihapus.');
		return redirect()->back();
	}
}

resources/views/admin/subjects/_box.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Mata Pelajaran</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>

    <div class="box-body">
        <ul class="products-list product-list-in-box">
            @forelse ($subjects as $s)
                <li class="item">
                    <div class="product-info">
                        <a href="{{ route('lms-admin.subjects.edit', $s) }}" class="product-title">
                            {{ $s->name }}
                        </a>
                        <span class="product-description">
                            {!! $s->description !!}
                        </span>
                    </div>
                </li>
            @empty
                <li class="item">                            
                    <div class="product-info">
                        Tidak ada ditemukan mata pelajaran baru.
                    </div>
                </li>
            @endforelse
        </ul>
    </div>

    <div class="box-footer text-center">
        <a href="{{ route('lms-admin.subjects.index') }}" class="uppercase">Lihat Semua Mata Pelajaran</a>
    </div>
</div>

resources/views/admin/subjects/_form.blade.php
<div class="box-body">
    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
        {!! Form::label('name', 'Nama', ['class' => 'col-md-3 control-label']) !!}
        <div class="col-md-6">
            {!! Form::text('name', null, ['class'=> 'form-control', 'autofocus' => 'autofocus', 'id' => 'name', 'autocomplete' => 'off']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>

    <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
        {!! Form::label('description', 'Deskripsi', ['class' => 'col-md-3 control-label']) !!}
        <div class="col-md-9">
            {!! Form::textarea('description', null, ['class' => 'form-control textarea', 'placeholder' => 'Deskripsi...', 'id' => 'description']) !!}
            {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
        </div>
    </div>

    <div class="box-footer">
        <div class="col-md-offset-3">
            {!! Form::submit(isset($model) ? 'Update' : 'Save', ['class'=>'btn btn-flat btn-success']) !!}
        </div>
    </div>
</div>

resources/views/admin/subjects/create.blade.php
@extends('admin.app')

@section('page_description')
    Menambahkan Mata Pelajaran
@endsection

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">&nbsp;</h3>
            </div>
            {!! Form::open(['role' => 'form', 'class' => 'form-horizontal', 'route' => 'lms-admin.subjects.store']) !!}
                @include('admin.subjects._form')
            {!! Form::close() !!}
        </div>
    </div>
    <div class="col-md-4">
        @include('admin.subjects._box', ['subjects' => $subjects])
    </div>
</div>
@endsection

resources/views/admin/subjects/edit.blade.php
@extends('admin.app')

@section('page_description')
    <a href="{{ route('lms-admin.subjects.create') }}" class="btn btn-flat btn-info btn-xs"><i class="fa fa-plus"></i> Tambah Baru</a>
@endsection

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $subject->name }}</h3>
            </div>
            {!! Form::model($subject, ['route' => ['lms-admin.subjects.update', $subject], 'method' =>'patch', 'role' => 'form', 'class' => 'form-horizontal']) !!}
                @include('admin.subjects._form', ['model' => $subject])
            {!! Form::close() !!}
        </div>
    </div>
    <div class="col-md-4">
        @include('admin.subjects._box', ['model' => $subjects])
    </div>
</div>
@endsection

resources/views/admin/subjects/index.blade.php
@extends('admin.app')

@section('page_description')
    <a href="{{ route('lms-admin.subjects.create') }}" class="btn btn-flat btn-info btn-xs"><i class="fa fa-plus"></i> Tambah Baru</a>
@endsection

@section('content')
<div class="row">
	<div class="pull-right col-xs-6 col-sm-4 col-md-3">

		{!! Form::open(['method' => 'get']) !!}
			<div class="form-group {!! $errors->has('title') ? 'has-error' : '' !!}">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-search"></i></span>
					{!! Form::text( 'q', Request::has('q') ? Request::get('q') : null, ['class' => 'form-control', 'placeholder' => 'Cari mata pelajaran...']) !!}
				</div>
			</div>
		{!! Form::close() !!}
		
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Tabel Kelas</h3>
			</div>
			<div class="box-body">
				<table id="subjects-datatable" class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>Kelas</th>
							<th>Mata Pelajaran</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($subjects as $classroom)
							<tr>
                <td>
                	<div>{{ $classroom->name }}</div>
                	<div>
                		<a href="{{ route('lms-admin.subjects.edit', $classroom->id) }}" class="btn btn-flat btn-link btn-xs">Edit</a>
  									{!! Form::open(['route' => ['lms-admin.subjects.destroy', $classroom->id], 'method' => 'delete', 'class' => 'form-delete-inline']) !!}
    									{!! Form::submit('Hapus', ['class'=>'btn btn-flat btn-link btn-link-danger btn-xs warning-delete', 'data-title' => $classroom->name]) !!}
    								{!! Form::close() !!}
                	</div>
                </td>
                <td>{!! $classroom->description !!}</td>
              </tr>
            @endforeach
          </tbody>
          <tfoot>
						<tr>
							<th>Nama</th>
							<th>Deskripsi</th>
						</tr>
					</tfoot>
				</table>
				<div class="pull-right">
				@if( Request::has('q') )
					{!! $subjects->appends(['q' => Request::get('q')])->links() !!}
				@else
					{!! $subjects->links() !!}
				@endif
				</div>
			</div>
		</div>
	</div>
</div><!-- /.row -->
@endsection