app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::get('/', ['uses' => 'LoginController@index', 'as' => 'login']);
Route::post('/auth/login', ['uses' => 'LoginController@login', 'as' => 'auth.login']);
Route::get('/auth/logout', ['uses' => 'LoginController@logout', 'as' => 'auth.logout']);

Route::group(['middleware' => ['auth', 'role:teacher|student']], function () {
	Route::put('/auth/profile', ['uses' => 'LoginController@update', 'as' => 'auth.update']);
	Route::put('/auth/password', ['uses' => 'LoginController@passwordUpdate', 'as' => 'auth.updatepassword']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::put('/auth/image', ['uses' => 'LoginController@changeImage', 'as' => 'auth.image']);
});

Route::post('/password/email', ['uses' => 'Auth\PasswordController@postEmail', 'as' => 'email.store']);
Route::get('/password/reset/{token}', ['uses' => 'Auth\PasswordController@getReset', 'as' => 'reset.request']);
Route::post('/password/reset', ['uses' => 'Auth\PasswordController@postReset', 'as' => 'reset.store']);

Route::group(['prefix' => '/lms-admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:staff']], function () {
	Route::get('/', ['uses' => 'HomeController@index', 'as' => 'lms-admin.index'] );
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'lms-admin.profile']);
	
	Route::resource('/users', 'UserController', ['except' => 'show']);
	Route::patch('users/{users}/usermeta', ['uses' => 'UserController@updateMeta', 'as' => 'lms-admin.users.updatemeta']);
	Route::resource('/majors', 'MajorController', ['except' => 'show']);
	Route::resource('/subjects', 'SubjectController', ['except' => 'show']);
	Route::resource('/announcements', 'AnnouncementController', ['except' => 'show']);
	Route::resource('/classrooms', 'ClassroomController', ['except' => 'show']);
	Route::post('/classrooms/addmembers', ['uses' => 'ClassroomController@addMembers', 'as' => 'lms-admin.classrooms.addmembers']);
	Route::post('/classrooms/removemember', ['uses' => 'ClassroomController@removeMember', 'as' => 'lms-admin.classrooms.removemember']);
});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
	Route::get('/{username}/profile', ['uses' => 'HomeController@friend', 'as' => 'home.friend']);
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'home.profile']);
	Route::get('/password', ['uses' => 'HomeController@password', 'as' => 'home.password']);
	Route::get('/calendar', ['uses' => 'HomeController@calendar', 'as' => 'home.calendar']);
	Route::get('/all-announcements', ['uses' => 'AnnouncementController@index', 'as' => 'home.announcements']);
	Route::get('/all-online', ['uses' => 'HomeController@online', 'as' => 'home.onlines']);
	Route::get('/all-assignments', ['uses' => 'AssignmentController@assignments', 'as' => 'home.assignments']);

	Route::get('/classrooms/{classrooms}', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.show']);
	Route::get('/classrooms/{classrooms}/edit', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.user.edit']);
	Route::post('/classrooms/{classrooms}', ['uses' => 'ClassroomController@update', 'as' => 'classrooms.user.update']);
	Route::get('/classrooms/{classrooms}/courses', ['uses' => 'ClassroomController@courses', 'as' => 'classrooms.courses']);
	Route::get('/classrooms/{classrooms}/assignments', ['uses' => 'ClassroomController@assignments', 'as' => 'classrooms.assignments']);
	Route::get('/classrooms/{classrooms}/quizzes', ['uses' => 'ClassroomController@quizzes', 'as' => 'classrooms.quizzes']);
	Route::get('/classrooms/{classrooms}/members', ['uses' => 'ClassroomController@members', 'as' => 'classrooms.members']);

	Route::get('/classrooms/{classrooms}/discuss/{discuss}', ['uses' => 'ClassroomController@discussionDetail', 'as' => 'classrooms.discussiondetail']);
	Route::get('/classrooms/{classrooms}/assignments/{assignments}', ['uses' => 'ClassroomController@assignmentDetail', 'as' => 'classrooms.assignmentdetail']);
	Route::get('/classrooms/{classrooms}/courses/{courses}', ['uses' => 'ClassroomController@courseDetail', 'as' => 'classrooms.coursedetail']);
	Route::get('/classrooms/{classrooms}/modules/{modules}', ['uses' => 'ClassroomController@moduleDetail', 'as' => 'classrooms.moduledetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}', ['uses' => 'ClassroomController@quizDetail', 'as' => 'classrooms.quizdetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}/score', ['uses' => 'ClassroomController@score', 'as' => 'classrooms.score']);
	Route::get('/classrooms/download/{filename}', ['uses' => 'ClassroomController@download', 'as' => 'classrooms.download']);

	Route::resource('/discuss', 'DiscussionController', ['only' => ['store', 'destroy']]);
	Route::post('/submission', ['uses' => 'ClassroomController@attachSubmission', 'as' => 'submissions.store']);
	Route::delete('/submission', ['uses' => 'ClassroomController@detachSubmission', 'as' => 'submissions.destroy']);

});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher']], function () {
	Route::resource('/assignments', 'AssignmentController', ['except' => 'show']);
	Route::post('/assignments/attach', ['uses' => 'AssignmentController@attachTo', 'as' => 'assignments.attach']);
	Route::post('/assignments/detach', ['uses' => 'AssignmentController@detachFrom', 'as' => 'assignments.detach']);
	
	Route::resource('/courses', 'CourseController', ['except' => 'show']);
	Route::post('/courses/attach', ['uses' => 'CourseController@attachTo', 'as' => 'courses.attach']);
	Route::post('/courses/detach', ['uses' => 'CourseController@detachFrom', 'as' => 'courses.detach']);

	Route::resource('/modules', 'ModuleController', ['except' => ['index', 'create', 'show']]);

	Route::resource('/quizzes', 'QuizController', ['except' => 'show']);
	Route::resource('/quizzes.mc', 'MultipleChoiceController', ['except' => ['index', 'show']]);
	Route::post('/quizzes/attach', ['uses' => 'QuizController@attachTo', 'as' => 'quizzes.attach']);
	Route::post('/quizzes/detach', ['uses' => 'QuizController@detachFrom', 'as' => 'quizzes.detach']);
});

Route::group(['prefix' => '/api', 'namespace' => 'API', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/assignments', 'AssignmentController@deadline');
	Route::post('/quizzes/start', 'QuizController@startQuiz');
	Route::post('/quizzes/submit', 'QuizController@submitQuiz');
	Route::post('/users/status', 'UserController@toggleStatus');
});

app/Models/Course.php
<?php

namespace App\Models;

use App\Traits\UuidModel;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
	use UuidModel;

	public $incrementing = false;

	protected $fillable = [
		'teacher_id', 'name', 'description', 'picture', 'level'
	];

	public function classrooms()
	{
		return $this->belongsToMany('App\Models\Classroom')->withTimestamps();
	}

	public function modules()
	{
		return $this->hasMany('App\Models\Module')->orderBy('created_at', 'ASC');
	}

	public function getAttachedToAttribute()
	{
		$ids = [];
		foreach ($this->classrooms as $classroom) {
			$ids[] = $classroom->id;
		}

		return $ids;
	}

	public function getAttachedClassroomAttribute()
	{
		$attached = [];
		foreach($this->classrooms as $class) {
			$attached[$class->id] = [
				'classname' => $class->classname
			];
		}
		return $attached;
	}

    public function getPictureSmAttribute()
    {
        return url('/uploads/courses/300x300-' . $this->picture);
    }
}

app/Models/Discussion.php
<?php

namespace App\Models;

use App\Traits\UuidModel;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Discussion extends Model
{
	use UuidModel;

	public $incrementing = false;

	protected $fillable = [
		'id', 'classroom_id', 'parent_id', 'user_id', 'content',
	];

	protected $hidden = [ 
		'comments'
	];

	public static function boot()
	{
		parent::boot();

		static::deleting(function($model){
			foreach ($model->comments as $comment) {
				if($comment) {
					$comment->delete();
				}
			}
		});
	}

	public function user()
	{
		return $this->belongsTo('App\Models\User');
	}

	public function comments()
	{
		return $this->hasMany('App\Models\Discussion', 'parent_id')->orderBy('created_at', 'DESC');
	}

	public function getPaginateCommentsAttribute()
	{
		return $this->comments()->limit(5)->get()->reverse();
	}

	public function getHumanTimeAttribute()
	{
		$now = Carbon::now();
		$created = Carbon::parse($this->created_at);

		if( $created->lt($now) ) {
			return $created->diffForHumans();
		} else {
			return $created->format('l jS F Y h:i:s A');
		}
	}
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
	public function toggleStatus(Request $request)
	{
		$this->validate($request, [
      'user_id' => 'required|exists:users,id'
    ]);

    $user = User::findOrFail($request->user_id);

    if($user->status === 'active') {
      $user->status = 'banned';
    } else {
      $user->status = 'active';
    }

    $user->save();

    return response()->json([
      'user_status' => $user->status
    ]);
	}
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Role;
use App\Models\User;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;

class UserController extends Controller
{
	public function index(Request $request)
	{
		$querystring = $this->buildQueryString($request);
		$users = $this->buildIndexQuery($request);
		$page_title = $request->has('q') ? 'Pencarian ' . $request->q : 'Semua Users';
		
		return view('admin.users.index', compact('users', 'querystring', 'page_title'));
	}

	public function buildQueryString($request)
	{
		$querystring = null;

		if( $request->has('type') ) {
			$querystring['type'] = $request->has('type') ? $request->type : '';
		} elseif($request->has('q')) {
			$querystring['q'] = $request->has('q') ? $request->q : '';
		}

		return $querystring;
	}

	public function buildIndexQuery($request)
	{
		if( $request->has('type') ) {            
			$users = User::where('role', $request->type)
				->orderBy('created_at', 'DESC')
				->paginate(7);
		} elseif( $request->has('q') ){
			$users = User::where(function($query) use ($request){
				$query->where('firstname', 'LIKE', '%' . $request->q . '%')
					->orWhere('lastname', 'LIKE', '%' . $request->q . '%')
					->orWhere('email', 'LIKE', '%' . $request->q . '%');
			})->orderBy('created_at', 'DESC')->paginate(7);
		} else {
			$users = User::orderBy('created_at', 'DESC')->paginate(7);
		}

		return $users;
	}

	public function create(Request $request)
	{
		$users = User::orderBy('created_at', 'DESC')->paginate(7);

		$page_title = $request->has('type') ? ucfirst($request->type) : 'User';
		return view('admin.users.create', compact('users', 'page_title'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'username' => 'required|unique:users,username',
			'firstname' => 'required',
			'lastname' => 'required',
			'email' => 'required|email|unique:users,email'
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!',
			'email' => 'Kolom :attribute harus berupa email.'
		]);

		$data = $request->all();
		//default password
		$data['password'] = bcrypt('secret');

		$user = User::create($data);

		$user->usermeta()->create([
			'picture' => 'icon-user-default.png',
			'cover' => 'cover-default.jpg'
		]);

		\Flash::success('User tersimpan.');
		return redirect()->route('lms-admin.users.edit', [$user->id]);
	}

	public function edit(Request $request, $id)
	{
		$users = User::orderBy('created_at', 'DESC')->paginate(7);
		$page_title = 'Edit User';
		$user = User::findOrFail($id);

		return view('admin.users.edit', compact('users', 'user', 'page_title'));
	}

	public function update(Request $request, $id)
	{
		$user = User::findOrFail($id);

		$this->validate($request, [
			'username' => 'required|unique:users,username,' . $user->id,
			'firstname' => 'required',
			'lastname' => 'required',
			'email' => 'required|email|unique:users,email,' . $user->id,
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!',
			'email' => 'Kolom :attribute harus berupa email.'
		]);
		
		$user->update($request->all());

		\Flash::success('User diperbaharui.');
		return redirect()->back();
	}

	public function updateMeta(Request $request, $id)
	{
		$user = User::findOrFail($id);

		if(!$user->hasRole('student')) {
			$request->except(['nis', 'nisn', 'orangtua', 'wali', 'telp_orangtua']);
		}

		$user->usermeta->update($request->all());

		\Flash::success('User diperbaharui.');
		return redirect()->back();
	}
	
	public function destroy($id)
	{
		User::findOrFail($id)->delete();

		\Flash::success('User berhasil dihapus.');
		return redirect()->back();
	}

}

app/Http/Controllers/User/AnnouncementController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Announcement;
use Illuminate\Http\Request;

class AnnouncementController extends Controller
{
  public function index()
  {
  	$announcements = Announcement::orderBy('created_at', 'DESC')->paginate(10);
  	$page_title = 'Pengumuman';

  	return view('user.global.announcements', compact('announcements', 'page_title'));
  }
}

app/Http/Controllers/User/DiscussionController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Discussion;
use Illuminate\Http\Request;
use Auth;

class DiscussionController extends Controller
{
	public function store(Request $request)
	{
		$this->validate($request, [
			'classroom_id' => 'required|exists:classrooms,id',
			'user_id' => 'required|exists:users,id',
			'content' => 'required'
		], [
			'exists' => 'Data :attribute belum terdaftar.',
			'required' => 'Kolom :attribute diperlukan!'
		]);

		Discussion::create($request->all());

		\Flash::success('Diskusi berhasil ditambahkan.');

		return redirect()->back();
	}

    public function destroy($id)
    {
    	Discussion::findOrFail($id)->delete();

      \Flash::success('Diskusi berhasil dihapus.');

      return redirect()->back();
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Activity;
use App\Models\Discussion;
use App\Models\User;
use Auth;
use Illuminate\Http\Request;

class HomeController extends Controller
{
	public function index()
	{
		$classroomIds = Auth::user()->joinedClassrooms;
		$activities = Activity::whereIn('classroom_id', $classroomIds)->orderBy('created_at', 'DESC')->paginate(10);
		$discussions = Discussion::where('parent_id', '')->whereIn('classroom_id', $classroomIds)->orderBy('created_at', 'DESC')->paginate(10);

		return view('user.global.feeds', compact('activities', 'discussions'));
	}

	public function profile()
	{
		$page_title = 'Profil';

		return view('user.global.profile', compact('page_title'));
	}

	public function password()
	{
		$page_title = 'Password';

		return view('user.global.password', compact('page_title'));
	}

	public function calendar()
	{
		$page_title = 'Kalender';

		return view('user.global.calendar', compact('page_title'));
	}

	public function online()
	{
		$users = User::onlineusers()->get();
		$page_title = 'Online';

		return view('user.global.onlines', compact('page_title', 'users'));
	}

	public function friend($username)
	{
		$user = User::where('username', $username)->first();
		$page_title = $user->fullname;

		return view('user.global.friend', compact('page_title', 'user'));
	}
}

resources/views/user/global/_tabs.blade.php
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active">
		<a href="#discussion" aria-controls="settings" role="tab" data-toggle="tab">Diskusi</a>
	</li>
</ul>

<div class="tab-content">
	<div role="tabpanel" class="tab-pane active" id="discussion">
		{!! Form::open(['route' => 'discuss.store']) !!}

			{!! Form::hidden('user_id', $lms['profile']->id) !!}

			<div class="form-group {{ $errors->has('content') ? 'has-error' : '' }}">
				{!! Form::textarea('content', null, ['class' => 'form-control discuss-textarea', 'placeholder' => 'Bagikan isi pikiran anda di tiap kelas...', 'rows' => '2']) !!}
				{!! $errors->first('content', '<p class="help-block">:message</p>') !!}
			</div>
			
			<div class="form-group {{ $errors->has('classroom_id') ? 'has-error' : '' }}"> 
				{!! Form::select('classroom_id', $lms['classrooms']->pluck('classname', 'id'), 'Pilih Kelas...', ['class' => 'select2 form-control', 'placeholder' => 'Pilih kelas...'])  !!}
				{!! $errors->first('classroom_id', '<p class="help-block">:message</p>') !!}
			</div>

			<div class="text-right"> 
				{!! Form::button('<i class="fa fa-send"></i> Bagikan', ['class'=>'btn btn-flat btn-primary', 'type' => 'submit']) !!}
			</div>

		{!! Form::close() !!}
	</div>
</div>

resources/views/user/global/announcements.blade.php
@extends('user.app')

@section('content')
<div class="container content">
	<div class="row">
		<div class="col-sm-3 col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Pemberitahuan</h2>
				</div>
				<ul class="list-group">
					<li class="list-group-item"><a class="text-small" href="{{ route('home.announcements') }}"><i class="fa fa-volume-up"></i> Pengumuman</a></li>
					<li class="list-group-item"><a class="text-small" href="{{ route('home.assignments') }}"><i class="fa fa-file"></i> Tugas</a></li>
					<li class="list-group-item"><a class="text-small" href="{{ route('home.onlines') }}"><i class="fa fa-circle"></i> Online</a></li>
				</ul>
			</div>
		</div>
		<div class="col-sm-5 col-md-7">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title text-bold">Pengumuman</h2>
				</div>
				<ul class="list-group">
					@foreach($announcements as $announcement)
					<li class="list-group-item">
						<article class="post announcement">
							<p>
								<strong><i class="fa fa-volume-up"></i> {{ $announcement->title }}</strong>
								<span class="status pull-right alert-{{ $announcement->status }}">{{ $announcement->urgensi }}</span>
							</p>
							<div>{!! $announcement->content !!}</div>
							<div>{{ $announcement->humantime }}</div>
						</article>
					</li>
					@endforeach
				</ul>
				<footer class="text-right">
					{{ $announcements->links() }}
				</footer>
			</div>
		</div>		
		<div class="col-sm-4 col-md-3 hidden-sm">
			@include( 'user.global.sidebars._sidebar-right' )
		</div>
	</div>
</div>
@endsection

resources/views/user/global/assignments.blade.php
@extends('user.app')

@section('content')
<div class="container content">
	<div class="row">
		<div class="col-sm-3 col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Pemberitahuan</h2>
				</div>
				<ul class="list-group">
					<li class="list-group-item"><a class="text-small" href="{{ route('home.announcements') }}"><i class="fa fa-volume-up"></i> Pengumuman</a></li>
					<li class="list-group-item"><a class="text-small" href="{{ route('home.assignments') }}"><i class="fa fa-file"></i> Tugas</a></li>
					<li class="list-group-item"><a class="text-small" href="{{ route('home.onlines') }}"><i class="fa fa-circle"></i> Online</a></li>
				</ul>
			</div>
		</div>
		<div class="col-sm-5 col-md-7">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title text-bold"><i class="fa fa-file"></i> {{ $page_title }}</h2>
				</div>
				<ul class="list-group">
					@foreach($assignments as $index => $assignment)
						<li class="list-group-item">
							<article class="post assignment">
								<strong>{{ $index + 1 }}. {{ $assignment->title }}</strong>
								<div>{!! $assignment->content !!}</div>
								<div>
									@can('manage')
										@foreach($assignment->classrooms as $classroom)
											<a class="btn btn-primary btn-sm" href="{{ route('classrooms.assignmentdetail', [$classroom->id, $assignment->id]) }}">
												<i class="fa fa-send"></i>
												{{ $classroom->classname }}
												<small>({{ formatDate($classroom->pivot->deadline) }})</small>
											</a>
										@endforeach
									@else
										<a class="btn btn-primary" href="{{ route('classrooms.assignmentdetail', [$assignment->classrooms->whereIn('id', $lms['profile']->joinedClassrooms)->first()->id, $assignment->id]) }}">
											<i class="fa fa-send"></i>
											Kerjakan
										</a>
									@endcan
								</div>
							</article>
						</li>
					@endforeach
				</ul>
				<footer class="text-right">
					{{ $assignments->links() }}
				</footer>
			</div>
		</div>		
		<div class="col-sm-4 col-md-3 hidden-sm">
			@include( 'user.global.sidebars._sidebar-right' )
		</div>
	</div>
</div>
@endsection

resources/views/user/global/feeds.blade.php
@extends('user.content')

@section('subcontent')
	<div class="panel panel-default new">
		<header class="classroom-header panel-heading">
			<h1 class="panel-title">Ingin mulai diskusi?</h1>
		</header>
		@include('user.global._tabs')
	</div>

	<ul class="nav nav-tabs feeds-tab-nav" role="tablist">
		<li role="presentation" class="active">
			<a href="#discussion-feeds" aria-controls="settings" role="tab" data-toggle="tab">Diskusi</a>
		</li>
		<li role="presentation">
			<a href="#activities-feeds" aria-controls="settings" role="tab" data-toggle="tab">Aktifitas</a>
		</li>
	</ul>

	<div class="tab-content feeds">
		<div role="tabpanel" class="tab-pane active" id="discussion-feeds">
			@forelse($discussions as $discuss)
				<div class="cpost-entry panel panel-default">
					<div class="panel-heading">
						<div class="media">
							<div class="media-left">
								<a href="#">
									<img class="media-object" src="{{ $discuss->user->picture_sm }}" alt="{{ $discuss->user->fullname }}">
								</a>
							</div>
							<div class="media-body">
								@can('delete-discussion', $discuss)
								<div class="pull-right">
									<div class="dropdown delete-post">
										<button class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<i class="fa fa-angle-down"></i>
										</button>
										<ul class="dropdown-menu">
											<li>
												{!! Form::open(['route' => ['discuss.destroy', $discuss->id], 'method' => 'delete', 'class' => 'form-delete-inline']) !!}
													{!! Form::hidden('classroom', $discuss->classroom_id) !!}
													{!! Form::submit('Hapus', ['class'=>'btn btn-link btn-sm']) !!}
												{!! Form::close() !!}
											</li>
										</ul>
									</div>
								</div>
								@endcan

								<h4 class="media-heading">{{ $discuss->user->fullname }}</h4>
								<p><small>{{ $discuss->human_time }}</small></p>
								<p class="text-small">{{ $discuss->content }}</p>
							</div>
						</div>
					</div>
					<ul class="list-group">
						@if($discuss->comments->count() > 5)
						<li class="list-group-item text-center"><a href="{{ route('classrooms.discussiondetail', [$discuss->classroom_id, $discuss]) }}" class="btn btn-link btn-sm">Lihat {{ $discuss->comments->count() - 5 }} komentar sebelumnya...</a></li>
						@endif
						@foreach($discuss->paginate_comments as $comment)
							<li class="list-group-item">
								<ul class="media-list comment">

										<li class="media text-small">
											<div class="media-left">
												<a href="#">
													<img class="media-object" src="{{ $comment->user->picture_sm }}" alt="{{ $comment->user->fullname }}">
												</a>
											</div>
											<div class="media-body">
												<h4 class="media-heading">{{ $comment->user->fullname }}</h4>
												<p><small>{{ $comment->human_time }}</small></p>
												<p>{{ $comment->content }}</p>
											</div>
										</li>

								</ul>
							</li>
						@endforeach
					</ul>

					<div class="reply panel-footer">
						<div class="media text-small">
							<div class="media-left">
								<a href="">
									<img class="media-object" src="{{ $lms['profile']->picture_sm }}">
								</a>
							</div>
							<div class="media-body">
								{!! Form::open(['route' => 'discuss.store']) !!}
									{!! Form::hidden('classroom_id', $discuss->classroom_id) !!}
									{!! Form::hidden('parent_id', $discuss->id) !!}
									{!! Form::hidden('user_id', $lms['profile']->id) !!}
									<div class="form-group {{ $errors->has('response') ? 'has-error' : '' }}">
										{!! Form::text('content', null, ['class' => 'form-control', 'placeholder' => 'Balas...', 'autocomplete' => 'off']) !!}
										{!! $errors->first('content', '<p class="help-block">:message</p>') !!}
									</div>
								{!! Form::close() !!}
							</div>
						</div>
					</div>
				</div>
			@empty
				<h3 class="text-center no-content">Tidak ada diskusi.</h3>
			@endforelse	
			<div class="text-right"> 
				{{ $discussions->links() }}
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="activities-feeds">
			@forelse($activities as $activity)
				<div class="panel panel-default feeds">
					<div class="panel-body">
						<p>
							<a href="{{ $activity->teacher_id == $lms['profile']->id ? route( 'home.profile') : route('home.friend', $activity->teacher->username) }}"><strong>{{ $activity->teacher->fullname }}</strong></a>
						</p>
						<p class="activity">{{ $activity->action }} 
							@can('manage')
								{{ $activity->classroom->classname }}
							@else
								<a href="{{ route($activity->route, [$activity->classroom->id, $activity->detail]) }}">{{ $activity->classroom->classname }}</a>.
							@endcan
						</p>
						<small>{{ formatDate($activity->created_at) }}</small>
					</div>
				</div>
			@empty
				<h3 class="text-center no-content">Tidak ada aktifitas.</h3>
			@endforelse	
			<div class="text-right"> 
				{{ $activities->links() }}
			</div>
		</div>
	</div>
@endsection