app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::get('/', ['uses' => 'LoginController@index', 'as' => 'login']);
Route::post('/auth/login', ['uses' => 'LoginController@login', 'as' => 'auth.login']);
Route::get('/auth/logout', ['uses' => 'LoginController@logout', 'as' => 'auth.logout']);

Route::group(['middleware' => ['auth', 'role:teacher|student']], function () {
	Route::put('/auth/profile', ['uses' => 'LoginController@update', 'as' => 'auth.update']);
	Route::put('/auth/password', ['uses' => 'LoginController@passwordUpdate', 'as' => 'auth.updatepassword']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::put('/auth/image', ['uses' => 'LoginController@changeImage', 'as' => 'auth.image']);
});

Route::post('/password/email', ['uses' => 'Auth\PasswordController@postEmail', 'as' => 'email.store']);
Route::get('/password/reset/{token}', ['uses' => 'Auth\PasswordController@getReset', 'as' => 'reset.request']);
Route::post('/password/reset', ['uses' => 'Auth\PasswordController@postReset', 'as' => 'reset.store']);

Route::group(['prefix' => '/lms-admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:staff']], function () {
	Route::get('/', ['uses' => 'HomeController@index', 'as' => 'lms-admin.index'] );
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'lms-admin.profile']);
	
	Route::resource('/users', 'UserController', ['except' => 'show']);
	Route::patch('users/{users}/usermeta', ['uses' => 'UserController@updateMeta', 'as' => 'lms-admin.users.updatemeta']);
	Route::resource('/majors', 'MajorController', ['except' => 'show']);
	Route::resource('/subjects', 'SubjectController', ['except' => 'show']);
	Route::resource('/announcements', 'AnnouncementController', ['except' => 'show']);
	Route::resource('/classrooms', 'ClassroomController', ['except' => 'show']);
	Route::post('/classrooms/addmembers', ['uses' => 'ClassroomController@addMembers', 'as' => 'lms-admin.classrooms.addmembers']);
	Route::post('/classrooms/removemember', ['uses' => 'ClassroomController@removeMember', 'as' => 'lms-admin.classrooms.removemember']);
});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
	Route::get('/{username}/profile', ['uses' => 'HomeController@friend', 'as' => 'home.friend']);
	Route::get('/profile',['uses' => 'HomeController@profile', 'as' => 'home.profile']);
	Route::get('/password', ['uses' => 'HomeController@password', 'as' => 'home.password']);
	Route::get('/calendar', ['uses' => 'HomeController@calendar', 'as' => 'home.calendar']);
	Route::get('/all-announcements', ['uses' => 'AnnouncementController@index', 'as' => 'home.announcements']);
	Route::get('/all-online', ['uses' => 'HomeController@online', 'as' => 'home.onlines']);
	Route::get('/all-assignments', ['uses' => 'AssignmentController@assignments', 'as' => 'home.assignments']);

	Route::get('/classrooms/{classrooms}', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.show']);
	Route::get('/classrooms/{classrooms}/edit', ['uses' => 'ClassroomController@show', 'as' => 'classrooms.user.edit']);
	Route::post('/classrooms/{classrooms}', ['uses' => 'ClassroomController@update', 'as' => 'classrooms.user.update']);
	Route::get('/classrooms/{classrooms}/courses', ['uses' => 'ClassroomController@courses', 'as' => 'classrooms.courses']);
	Route::get('/classrooms/{classrooms}/assignments', ['uses' => 'ClassroomController@assignments', 'as' => 'classrooms.assignments']);
	Route::get('/classrooms/{classrooms}/quizzes', ['uses' => 'ClassroomController@quizzes', 'as' => 'classrooms.quizzes']);
	Route::get('/classrooms/{classrooms}/members', ['uses' => 'ClassroomController@members', 'as' => 'classrooms.members']);

	Route::get('/classrooms/{classrooms}/discuss/{discuss}', ['uses' => 'ClassroomController@discussionDetail', 'as' => 'classrooms.discussiondetail']);
	Route::get('/classrooms/{classrooms}/assignments/{assignments}', ['uses' => 'ClassroomController@assignmentDetail', 'as' => 'classrooms.assignmentdetail']);
	Route::get('/classrooms/{classrooms}/courses/{courses}', ['uses' => 'ClassroomController@courseDetail', 'as' => 'classrooms.coursedetail']);
	Route::get('/classrooms/{classrooms}/modules/{modules}', ['uses' => 'ClassroomController@moduleDetail', 'as' => 'classrooms.moduledetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}', ['uses' => 'ClassroomController@quizDetail', 'as' => 'classrooms.quizdetail']);
	Route::get('/classrooms/{classrooms}/quizzes/{quizzes}/score', ['uses' => 'ClassroomController@score', 'as' => 'classrooms.score']);
	Route::get('/classrooms/download/{filename}', ['uses' => 'ClassroomController@download', 'as' => 'classrooms.download']);

	Route::resource('/discuss', 'DiscussionController', ['only' => ['store', 'destroy']]);
	Route::post('/submission', ['uses' => 'ClassroomController@attachSubmission', 'as' => 'submissions.store']);
	Route::delete('/submission', ['uses' => 'ClassroomController@detachSubmission', 'as' => 'submissions.destroy']);

});

Route::group(['namespace' => 'User', 'middleware' => ['auth', 'role:teacher']], function () {
	Route::resource('/assignments', 'AssignmentController', ['except' => 'show']);
	Route::post('/assignments/attach', ['uses' => 'AssignmentController@attachTo', 'as' => 'assignments.attach']);
	Route::post('/assignments/detach', ['uses' => 'AssignmentController@detachFrom', 'as' => 'assignments.detach']);
	
	Route::resource('/courses', 'CourseController', ['except' => 'show']);
	Route::post('/courses/attach', ['uses' => 'CourseController@attachTo', 'as' => 'courses.attach']);
	Route::post('/courses/detach', ['uses' => 'CourseController@detachFrom', 'as' => 'courses.detach']);

	Route::resource('/modules', 'ModuleController', ['except' => ['index', 'create', 'show']]);

	Route::resource('/quizzes', 'QuizController', ['except' => 'show']);
	Route::resource('/quizzes.mc', 'MultipleChoiceController', ['except' => ['index', 'show']]);
	Route::post('/quizzes/attach', ['uses' => 'QuizController@attachTo', 'as' => 'quizzes.attach']);
	Route::post('/quizzes/detach', ['uses' => 'QuizController@detachFrom', 'as' => 'quizzes.detach']);
});

Route::group(['prefix' => '/api', 'namespace' => 'API', 'middleware' => ['auth', 'role:teacher|student']], function () {
	Route::get('/assignments', 'AssignmentController@deadline');
	Route::post('/quizzes/start', 'QuizController@startQuiz');
	Route::post('/quizzes/submit', 'QuizController@submitQuiz');
	Route::post('/users/status', 'UserController@toggleStatus');
});

app/Models/Course.php
<?php

namespace App\Models;

use App\Traits\UuidModel;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
	use UuidModel;

	public $incrementing = false;

	protected $fillable = [
		'teacher_id', 'name', 'description', 'picture', 'level'
	];

	public function classrooms()
	{
		return $this->belongsToMany('App\Models\Classroom')->withTimestamps();
	}

	public function modules()
	{
		return $this->hasMany('App\Models\Module')->orderBy('created_at', 'ASC');
	}

	public function getAttachedToAttribute()
	{
		$ids = [];
		foreach ($this->classrooms as $classroom) {
			$ids[] = $classroom->id;
		}

		return $ids;
	}

	public function getAttachedClassroomAttribute()
	{
		$attached = [];
		foreach($this->classrooms as $class) {
			$attached[$class->id] = [
				'classname' => $class->classname
			];
		}
		return $attached;
	}

    public function getPictureSmAttribute()
    {
        return url('/uploads/courses/300x300-' . $this->picture);
    }
}

app/Models/Discussion.php
<?php

namespace App\Models;

use App\Traits\UuidModel;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Discussion extends Model
{
	use UuidModel;

	public $incrementing = false;

	protected $fillable = [
		'id', 'classroom_id', 'parent_id', 'user_id', 'content',
	];

	protected $hidden = [ 
		'comments'
	];

	public static function boot()
	{
		parent::boot();

		static::deleting(function($model){
			foreach ($model->comments as $comment) {
				if($comment) {
					$comment->delete();
				}
			}
		});
	}

	public function user()
	{
		return $this->belongsTo('App\Models\User');
	}

	public function comments()
	{
		return $this->hasMany('App\Models\Discussion', 'parent_id')->orderBy('created_at', 'DESC');
	}

	public function getPaginateCommentsAttribute()
	{
		return $this->comments()->limit(5)->get()->reverse();
	}

	public function getHumanTimeAttribute()
	{
		$now = Carbon::now();
		$created = Carbon::parse($this->created_at);

		if( $created->lt($now) ) {
			return $created->diffForHumans();
		} else {
			return $created->format('l jS F Y h:i:s A');
		}
	}
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
	public function toggleStatus(Request $request)
	{
		$this->validate($request, [
      'user_id' => 'required|exists:users,id'
    ]);

    $user = User::findOrFail($request->user_id);

    if($user->status === 'active') {
      $user->status = 'banned';
    } else {
      $user->status = 'active';
    }

    $user->save();

    return response()->json([
      'user_status' => $user->status
    ]);
	}
}

app/Http/Controllers/Admin/ClassroomController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Models\Classroom;

class ClassroomController extends Controller
{
	public function index(Request $request)
	{
		$classrooms = Classroom::orderBy('created_at', 'DESC')->paginate(7);
		$page_title = 'Semua Kelas';

		return view('admin.classrooms.index', compact('classrooms', 'page_title'));
	}

	public function create()
	{
		$page_title = 'Tambah Kelas';
		
		return view('admin.classrooms.create', compact('classrooms', 'page_title'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'grade' => 'required',
			'major_id' => 'required|exists:majors,id',
			'subject_id' => 'required|exists:subjects,id',
			'teacher_id' => 'required',
			'description' => 'required'
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!'
		]);

		$classroom = Classroom::create($request->all());

		\Flash::success('Kelas berhasil dibuat.');
		return redirect()->route('lms-admin.classrooms.edit', [$classroom->id]);
	}

	public function edit($id)
	{
		$classroom = Classroom::findOrFail($id);
		$students = $classroom->students()->where('role', 'student')->paginate(5, ['*'], 's_page');
		$page_title = 'Manage Kelas';

		$ids = $classroom->students->pluck('id');

		return view('admin.classrooms.edit', compact('classroom', 'page_title', 'students', 'ids'));
	}

	public function update(Request $request, $id)
	{
		$classroom = Classroom::findOrFail($id);

		$this->validate($request, [
			'grade' => 'required',
			'major_id' => 'required|exists:majors,id',
			'subject_id' => 'required|exists:subjects,id',
			'teacher_id' => 'required|exists:users,id',
			'description' => 'required'
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!'
		]);

		$classroom->update($request->all());

		\Flash::success('Kelas berhasil diubah.');
		return redirect()->back();
	}

	public function destroy($id)
	{
		Classroom::findOrFail($id)->delete();

		\Flash::success('Kelas berhasil dihapus.');
		return redirect()->back();
	}

	public function addMembers(Request $request)
	{
		$this->validate($request, [
			'students' => 'required|exists:users,id'
		], [
			'required' => 'Kolom :attribute tidak boleh kosong!',
			'exists' => 'Kolom :attribute tidak ditemukan!'
		]);

		$classroom = Classroom::findOrFail($request->classroom_id);
		$classroom->students()->sync($request->students, false);

		\Flash::success('Member berhasil ditambahkan.');
		return redirect()->back();
	}

	public function removeMember(Request $request) 
	{
		$classroom = Classroom::findOrFail($request->classroom_id);
		$classroom->students()->detach($request->user_id);

		\Flash::success('User berhasil dihapus dari kelas.');
		return redirect()->back();
	}
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Role;
use App\Models\User;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;

class UserController extends Controller
{
	public function index(Request $request)
	{
		$querystring = $this->buildQueryString($request);
		$users = $this->buildIndexQuery($request);
		$page_title = $request->has('q') ? 'Pencarian ' . $request->q : 'Semua Users';
		
		return view('admin.users.index', compact('users', 'querystring', 'page_title'));
	}

	public function buildQueryString($request)
	{
		$querystring = null;

		if( $request->has('type') ) {
			$querystring['type'] = $request->has('type') ? $request->type : '';
		} elseif($request->has('q')) {
			$querystring['q'] = $request->has('q') ? $request->q : '';
		}

		return $querystring;
	}

	public function buildIndexQuery($request)
	{
		if( $request->has('type') ) {            
			$users = User::where('role', $request->type)
				->orderBy('created_at', 'DESC')
				->paginate(7);
		} elseif( $request->has('q') ){
			$users = User::where(function($query) use ($request){
				$query->where('firstname', 'LIKE', '%' . $request->q . '%')
					->orWhere('lastname', 'LIKE', '%' . $request->q . '%')
					->orWhere('email', 'LIKE', '%' . $request->q . '%');
			})->orderBy('created_at', 'DESC')->paginate(7);
		} else {
			$users = User::orderBy('created_at', 'DESC')->paginate(7);
		}

		return $users;
	}

	public function create(Request $request)
	{
		$users = User::orderBy('created_at', 'DESC')->paginate(7);

		$page_title = $request->has('type') ? ucfirst($request->type) : 'User';
		return view('admin.users.create', compact('users', 'page_title'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'username' => 'required|unique:users,username',
			'firstname' => 'required',
			'lastname' => 'required',
			'email' => 'required|email|unique:users,email'
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!',
			'email' => 'Kolom :attribute harus berupa email.'
		]);

		$data = $request->all();
		//default password
		$data['password'] = bcrypt('secret');

		$user = User::create($data);

		$user->usermeta()->create([
			'picture' => 'icon-user-default.png',
			'cover' => 'cover-default.jpg'
		]);

		\Flash::success('User tersimpan.');
		return redirect()->route('lms-admin.users.edit', [$user->id]);
	}

	public function edit(Request $request, $id)
	{
		$users = User::orderBy('created_at', 'DESC')->paginate(7);
		$page_title = 'Edit User';
		$user = User::findOrFail($id);

		return view('admin.users.edit', compact('users', 'user', 'page_title'));
	}

	public function update(Request $request, $id)
	{
		$user = User::findOrFail($id);

		$this->validate($request, [
			'username' => 'required|unique:users,username,' . $user->id,
			'firstname' => 'required',
			'lastname' => 'required',
			'email' => 'required|email|unique:users,email,' . $user->id,
		], [
			'required' => 'Kolom :attribute diperlukan!',
			'exists' => 'Kolom :attribute tidak ditemukan!',
			'email' => 'Kolom :attribute harus berupa email.'
		]);
		
		$user->update($request->all());

		\Flash::success('User diperbaharui.');
		return redirect()->back();
	}

	public function updateMeta(Request $request, $id)
	{
		$user = User::findOrFail($id);

		if(!$user->hasRole('student')) {
			$request->except(['nis', 'nisn', 'orangtua', 'wali', 'telp_orangtua']);
		}

		$user->usermeta->update($request->all());

		\Flash::success('User diperbaharui.');
		return redirect()->back();
	}
	
	public function destroy($id)
	{
		User::findOrFail($id)->delete();

		\Flash::success('User berhasil dihapus.');
		return redirect()->back();
	}

}

app/Http/Controllers/User/AnnouncementController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Announcement;
use Illuminate\Http\Request;

class AnnouncementController extends Controller
{
  public function index()
  {
  	$announcements = Announcement::orderBy('created_at', 'DESC')->paginate(10);
  	$page_title = 'Pengumuman';

  	return view('user.global.announcements', compact('announcements', 'page_title'));
  }
}

resources/views/user/classrooms/_tabs.blade.php
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active">
		<a href="#discussion" aria-controls="settings" role="tab" data-toggle="tab">Diskusi</a>
	</li>
	@can('manage')
	<li role="presentation">
		<a href="#module" aria-controls="settings" role="tab" data-toggle="tab">Materi</a>
	</li>
	<li role="presentation">
		<a href="#assignment" aria-controls="settings" role="tab" data-toggle="tab">Tugas</a>
	</li>
	<li role="presentation">
		<a href="#quiz" aria-controls="settings" role="tab" data-toggle="tab">Quiz</a>
	</li>
	@endcan
</ul>

<div class="tab-content">
	<div role="tabpanel" class="tab-pane active" id="discussion">
		{!! Form::open(['route' => 'discuss.store']) !!}

			{!! Form::hidden('classroom_id', $classroom->id) !!}
			{!! Form::hidden('user_id', $lms['profile']->id) !!}

			<div class="form-group {{ $errors->has('content') ? 'has-error' : '' }}">
				{!! Form::textarea('content', null, ['class' => 'form-control discuss-textarea', 'placeholder' => 'Bagikan isi pikiran anda dikelas ini...', 'rows' => '2']) !!}
				{!! $errors->first('content', '<p class="help-block">:message</p>') !!}
			</div>

			<div class="text-right"> 
				{!! Form::button('<i class="fa fa-send"></i> Bagikan', ['class'=>'btn btn-flat btn-primary', 'type' => 'submit', 'id' => 'submitDiscussion']) !!}
			</div>

		{!! Form::close() !!}
	</div>
	@can('manage')
	<div role="tabpanel" class="tab-pane" id="module">
		<div class="text-center">
			<a href="#" data-toggle="modal" data-target="#courseModal">Pilih Materi</a> <span class="atau">atau</span> <a href="{{ route('courses.create') }}" class="btn btn-primary">Buat Materi Baru</a>
		</div>
	</div>
	<div role="tabpanel" class="tab-pane" id="assignment">
		<div class="text-center">
			<a href="#" data-toggle="modal" data-target="#assignmentsModal">Pilih Tugas</a> <span class="atau">atau</span> <a href="{{ route('assignments.create') }}" class="btn btn-primary">Buat Tugas Baru</a>
		</div>
	</div>
	<div role="tabpanel" class="tab-pane" id="quiz">
		<div class="text-center">
			<a href="#" data-toggle="modal" data-target="#quizzesModal">Pilih Quiz</a> <span class="atau">atau</span> <a href="{{ route('quizzes.create') }}" class="btn btn-primary">Buat Quiz Baru</a>
		</div>
	</div>
	@endcan
</div>

<div class="modal fade" id="quizzesModal" tabindex="-1" role="dialog" aria-labelledby="shareQuiz">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="shareQuiz">Bagikan quiz di kelas ini</h4>
			</div>
			{!! Form::open(['route' => ['quizzes.attach'], 'method' => 'post', 'role' => 'form', 'class' => 'form-horizontal']) !!}
				<div class="modal-body clearfix">
					<div class="col-md-12">
						{!! Form::hidden('classroom_id', $classroom->id) !!}
						<div class="form-group {{ $errors->has('quiz_id') ? 'has-error' : '' }}"> 
						{!! Form::select('quiz_id', $lms['profile']->teacherquizzes()->whereNotIn('id', $classroom->attachedQuizzes)->get()->pluck('title', 'id'), null, ['class' => 'select2 form-control', 'placeholder' => 'Pilih quiz...'])  !!}
						{!! $errors->first('quiz_id', '<p class="help-block">:message</p>') !!}
						</div>
					</div>
				</div>
				<div class="modal-footer">
					{!! Form::button('Batal', ['class' => 'btn btn-link', 'data-dismiss' => 'modal']) !!}
					{!! Form::button('<i class="fa fa-share-alt"></i> Bagikan Quiz', ['class' => 'btn btn-primary', 'type' => 'submit']) !!}
				</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

<div class="modal fade" id="assignmentsModal" tabindex="-1" role="dialog" aria-labelledby="shareAssignment">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="shareAssignment">Bagikan tugas ini</h4>
			</div>
			{!! Form::open(['route' => ['assignments.attach'], 'method' => 'post', 'role' => 'form', 'class' => 'form-horizontal']) !!}
				<div class="modal-body clearfix">
					<div class="col-md-12">
						{!! Form::hidden('classroom_id', $classroom->id) !!}
						<div class="form-group {{ $errors->has('assignment_id') ? 'has-error' : '' }}"> 
						{!! Form::select('assignment_id', $lms['profile']->teacherassignments()->whereNotIn('id', $classroom->attachedAssignments)->get()->pluck('title', 'id'), null, ['class' => 'select2 form-control', 'placeholder' => 'Pilih tugas...'])  !!}
						{!! $errors->first('assignment_id', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group {{ $errors->has('deadline') ? 'has-error' : '' }}"> 
						{!! Form::text('deadline', null, ['class' => 'form-control datepicker', 'placeholder' => 'Deadline']) !!}
						{!! $errors->first('deadline', '<p class="help-block">:message</p>') !!}
						</div>
					</div>
				</div>
				<div class="modal-footer">
					{!! Form::button('Batal', ['class' => 'btn btn-link', 'data-dismiss' => 'modal']) !!}
					{!! Form::button('<i class="fa fa-share-alt"></i> Bagikan Tugas', ['class' => 'btn btn-primary', 'type' => 'submit']) !!}
				</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

<div class="modal fade" id="courseModal" tabindex="-1" role="dialog" aria-labelledby="shareCourse">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Bagikan Materi ini</h4>
			</div>
			{!! Form::open(['route' => ['courses.attach'], 'method' => 'post', 'role' => 'form', 'class' => 'form-horizontal']) !!}
				<div class="modal-body clearfix">
					<div class="col-md-12">
						{!! Form::hidden('classroom_id', $classroom->id) !!}
						<div class="form-group {{ $errors->has('course_id') ? 'has-error' : '' }}"> 
						{!! Form::select('course_id', $lms['profile']->teachercourses()->whereNotIn('id', $classroom->attachedCourses)->get()->pluck('name', 'id'), null, ['class' => 'select2 form-control', 'placeholder' => 'Pilih materi...'])  !!}
						{!! $errors->first('course_id', '<p class="help-block">:message</p>') !!}
						</div>
					</div>
				</div>
				<div class="modal-footer">
					{!! Form::button('Batal', ['class' => 'btn btn-link', 'data-dismiss' => 'modal']) !!}
					{!! Form::button('<i class="fa fa-share-alt"></i> Bagikan Materi', ['class' => 'btn btn-primary', 'type' => 'submit']) !!}
				</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

resources/views/user/classrooms/assignments.blade.php
@extends('user.classrooms.classroom')

@section('classroom_content')
	@forelse($classroom->paginateAvailableAssignments as $assignment)
		<div class="panel panel-default">
			<header class="panel-heading">
				<h2 class="panel-title">{{ $assignment->title }}</h2>
			</header>
			<ul class="list-group">
				<li class="list-group-item">{!! $assignment->content !!}</li>

				<li class="list-group-item"><span class="text-small"><strong>Deadline:</strong> {{ formatDate($assignment->pivot->deadline) }}</span></li>
				@if($assignment->file)
					<li class="list-group-item"><span class="attached"><i class="fa fa-cloud-download"></i></span><a href="{{ route('classrooms.download', $assignment->file) }}">{{ $assignment->file }}</a></li>
				@endif
			</ul>
			<div class="panel-footer text-right">
				<a href="{{ route('classrooms.assignmentdetail', [$classroom->id, $assignment->id]) }}" class="btn btn-primary">@can('manage') Detail @else Kerjakan @endcan</a>
			</div>
		</div>
	@empty
		<h4 class="text-center no-content">Belum ada tugas diberikan untuk kelas ini.</h4>
	@endforelse
	{{ $classroom->paginateAvailableAssignments->links() }}
@endsection

resources/views/user/classrooms/courses.blade.php
@extends('user.classrooms.classroom')

@section('classroom_content')
	@forelse($classroom->courses as $course)
		<div class="panel panel-default">
			<header class="panel-heading">
				<h2 class="panel-title text-bold">{{ $course->name }}</h2>
			</header>
			<ul class="list-group">
				<li class="list-group-item">{!! $course->description !!}</li>
			</ul>
			<div class="panel-footer text-right">
				<a href="{{ route('classrooms.coursedetail', [$classroom->id, $course->id]) }}" class="btn btn-primary">@can('manage') Detail @else Pelajari @endcan</a>
			</div>
		</div>
	@empty
		<h4 class="text-center no-content">Belum ada materi diberikan untuk kelas ini.</h4>
	@endforelse
@endsection

resources/views/user/classrooms/quiz-end.blade.php
@extends('user.app')

@section('content')	
  <div class="container" id="luar" style="padding-top: 100px;">
    <div class="row">
      <div class="col-sm-12 text-center">
      	<h1 class="no-content">Maaf, quiz sudah selesai :)</h1>
      	<p>Silakan <a href="{{ route('classrooms.show', $classroom->id) }}">kembali.</a></p>
      </div>
   </div>
 </div>
@endsection